### ISSUE TITLE
Flag -f/-folder produces "octree already built" error 

### ISSUE THREAD

**Issue by majos95** [mfbonfigli/gocesiumtiler#20] opened 2021-07-22 08:30 UTC
After trying it with different Point Clouds, flag -f does not seem to work. After correctly processing the first file, an "octree already built" error appears.

**Comment by mfbonfigli** [comment] 2021-07-22 21:38
Oh totally right. I think the issue is here https://github.com/mfbonfigli/gocesiumtiler/blob/71716873b114f1b1f420af17d89de9446761e0ba/pkg/tiler.go#L43
line 43 should be inside the for loop. If you want to check it out and submit a CR happy to review it :)

**Comment by majos95** [comment] 2021-07-23 11:06
That did not fix it, but it led me to the solution, the problem is on the Build() itself. I'll submit a CR as soon as possible.

**Comment by mfbonfigli** [comment] 2021-07-23 19:47
Interesting, I would have expected that small change to fix it. Feel free to send a CR out, in the meanwhile I'll try to do some experiments on my side.

**Comment by lopez-loic** [comment] 2021-11-10 13:15
Any updates on this issue?

**Comment by mfbonfigli** [comment] 2021-11-14 12:19
I just released a new version 1.2.1 that should hopefully fix this. Please give it a try. Closing the issue for now, feel free to reopen it or create a new one if the issue persists.

**Closed by mfbonfigli** 2021-11-14 12:19 UTC
Labels: bug
