### ISSUE TITLE
The projection caused the height offset ?（My input is EPSG:2326）

### ISSUE THREAD

**Issue by LeoLiJingWen** [mfbonfigli/gocesiumtiler#30] opened 2023-05-18 12:00 UTC
![image](https://github.com/mfbonfigli/gocesiumtiler/assets/105909989/88944889-ea44-4d20-9e65-83666daef4f0)
According to the above image：

The point cloud at the bottom was transformed using gocesiumtiler

The mesh at the top is a gltf file which was generated from the same point cloud file
I use pyproj(proj==9.0.0) to transform the coordinates from EPSG:2326 to EPSG:4978

The final display on Cesium shows that the gltf is correct in position and height, while the point cloud is correct in position but incorrect in height. What causes it? 

My conversion command is as follows: 

gocesiumtiler -i ./ hk.las -o ./ cesium -e 2326 -n 1.5

**Comment by mfbonfigli** [comment] 2023-05-21 10:22
Hello,

I'm not quite sure what could be causing it. 

Did you try to add the `-g` parameter to the converter?  Z coordinates could be expressed as elevation above the ellipsoid or above the geoid. gocesiumtiler assumes by default that the elevation is defined as above the ellipsoid as that's the Cesium expectation. If you pass the `-g` flag it will interpret the Z as above the geoid and attempt to convert it to ellipsoid elevation.

I'm not however sure if this is the issue at play here.

**Comment by LeoLiJingWen** [comment] 2023-05-22 04:20
Thank you very much for your reply. 

I have tried to add the -g parameter to convert the point cloud, but I waited for a long time and the command was still executing (as shown below). Eventually I gave up, I am not sure if running for a sufficient amount of time would allow the command to complete executing. Without the -g parameter, the command completed executing very quickly. 
![image](https://github.com/mfbonfigli/gocesiumtiler/assets/105909989/de6da4ca-b45a-44d2-a001-4ffa982dd44b)

Here are some basic information about the point cloud(open in CloudCompare), the file size is 113MB. 
![image](https://github.com/mfbonfigli/gocesiumtiler/assets/105909989/616797d0-cacc-401f-b793-9b40014945d7)

**Comment by LeoLiJingWen** [comment] 2023-05-25 04:34
![image](https://github.com/mfbonfigli/gocesiumtiler/assets/105909989/dfc9e3ab-a24d-4931-b014-91ec1e8f20b7)
the command executed for over 16 hours and the status was still "exporting data", so I eventually had to terminate it.

**Comment by mfbonfigli** [comment] 2023-07-03 19:18
Hi, 16 hours for a 100mb file is definitely too much, a file of that size on a modern computer should normally take minutes to complete. Without data to debug the issue is however hard for me to figure out what is happening here. Please consider if you could send me a sample to troubleshoot

**Comment by mfbonfigli** [comment] 2024-06-03 09:55
Closing this one. I followed up offline with [LeoLiJingWen](https://github.com/LeoLiJingWen) and the issue was solved with the version `v1.2.3` which improved LAS 1.4 compatibility.

**Closed by mfbonfigli** 2024-06-03 09:55 UTC
