### ISSUE TITLE
"Octree Already Built" Error on Folder Mode

### ISSUE THREAD

**Issue by schroedermarc** [mfbonfigli/gocesiumtiler#23] opened 2021-12-13 23:48 UTC
Hello, having an issue when running on MacOS Monterey (ARM). 

Individual .LAS files are tiled perfectly, but getting a "octree already built" error on the second file, no matter the file, when run on a folder of .LAS files. I've tried changing the various algorithms and other flags and with different sets of files. It always crashes this same way on the second file. Is this a bug? or am I missing a flag or option?

example command `gocesiumtiler -i ../smaller/ -o ../output/ -folder -r -b`

example output:

![image](https://user-images.githubusercontent.com/34323315/145907023-651b43e5-babc-45c2-a566-2fca1b55d0e7.png)

**Comment by schroedermarc** [comment] 2021-12-14 18:22
Just noticing this is a duplicate of #20, however the issue is persisting on v1.2.1 in my experience.

**Comment by mfbonfigli** [comment] 2022-01-05 20:16
Thanks for your feedback @schroedermarc. I will try to further investigate the issue to understand the root cause. If you have a couple of small las files to use to reproduce the issue that would be helpful.

Thanks!

**Comment by mfbonfigli** [comment] 2022-01-07 17:40
I was able to reproduce the problem and I can confirm that the issue is still present on release 1.2.1. 
I just published a new release 1.2.2 that should hopefully fix this issue. Leaving this open for a while to allow users to put comments in case the issue is still persisting.

**Comment by schroedermarc** [comment] 2022-01-18 19:21
@mfbonfigli, it works now in 1.2.2! I Realized I had misunderstood what the output would be when it works. I had thought it would create a single tiles folder with a combined output. Now I'm seeing that was never intended to be the case. So that's the next thing to solve for me. Please let me know if any tool comes to mind. Otherwise I think this issue is solved from my perspective. I'll let you control when the issue closes. Thanks!

**Comment by mfbonfigli** [comment] 2022-05-10 21:35
A few months have passed, I'm going to close this issue! Thanks for the feedback!

**Closed by mfbonfigli** 2022-05-10 21:35 UTC
